[2024-02-10T23:54:47.447+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:53:48.513364+00:00 [queued]>
[2024-02-10T23:54:47.561+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:53:48.513364+00:00 [queued]>
[2024-02-10T23:54:47.569+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T23:54:47.731+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-02-10 23:53:48.513364+00:00
[2024-02-10T23:54:47.798+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-02-10T23:54:48.155+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'send_email_task', 'manual__2024-02-10T23:53:48.513364+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmplr_vqy0b']
[2024-02-10T23:54:48.488+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask send_email_task
[2024-02-10T23:54:50.549+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:53:48.513364+00:00 [running]> on host 2012a0ecf4b3
[2024-02-10T23:54:59.760+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T23:53:48.513364+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T23:53:48.513364+00:00'
[2024-02-10T23:54:59.885+0000] {etl_dag.py:184} INFO - Tipo de datos temp: float64
[2024-02-10T23:54:59.887+0000] {etl_dag.py:188} INFO - min temp: 5.0
[2024-02-10T23:54:59.888+0000] {etl_dag.py:191} INFO - max temp: 30.0
[2024-02-10T23:54:59.905+0000] {etl_dag.py:242} ERROR - cannot set a frame with no defined index and a scalar
[2024-02-10T23:54:59.907+0000] {etl_dag.py:243} ERROR - Error al enviar el correo electr√≥nico.
[2024-02-10T23:54:59.912+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T23:54:59.995+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=send_email_task, execution_date=20240210T235348, start_date=20240210T235447, end_date=20240210T235459
[2024-02-10T23:55:00.157+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T23:55:01.371+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
