[2024-02-10T23:18:06.758+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.extract manual__2024-02-10T23:18:03.970125+00:00 [queued]>
[2024-02-10T23:18:06.792+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.extract manual__2024-02-10T23:18:03.970125+00:00 [queued]>
[2024-02-10T23:18:06.794+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T23:18:06.844+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 23:18:03.970125+00:00
[2024-02-10T23:18:06.863+0000] {standard_task_runner.py:60} INFO - Started process 72 to run task
[2024-02-10T23:18:06.875+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'extract', 'manual__2024-02-10T23:18:03.970125+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpb6x7hdgo']
[2024-02-10T23:18:06.885+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask extract
[2024-02-10T23:18:07.106+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.extract manual__2024-02-10T23:18:03.970125+00:00 [running]> on host 79b2a2ac03ce
[2024-02-10T23:18:07.673+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T23:18:03.970125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T23:18:03.970125+00:00'
[2024-02-10T23:18:08.789+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-34.61, -58.38) OK.
[2024-02-10T23:18:09.920+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-56.18, -34.9) OK.
[2024-02-10T23:18:10.973+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (135.18, 34.69).
[2024-02-10T23:18:11.998+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-0.12, 51.5) OK.
[2024-02-10T23:18:13.051+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (-118.24, 34.05).
[2024-02-10T23:18:14.153+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-60.02, -3.1) OK.
[2024-02-10T23:18:15.190+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-80.19, 25.77) OK.
[2024-02-10T23:18:16.239+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-66.1, 18.46) OK.
[2024-02-10T23:18:17.287+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (121.45, 31.22).
[2024-02-10T23:18:17.336+0000] {etl_dag.py:88} INFO - Contenido del DataFrame después de la extracción:
                            coord  ...  cod
0  {'lon': -58.38, 'lat': -34.61}  ...  200
1   {'lon': -34.9, 'lat': -56.18}  ...  200
2     {'lon': 51.5, 'lat': -0.12}  ...  200
3    {'lon': -3.1, 'lat': -60.02}  ...  200
4   {'lon': 25.77, 'lat': -80.19}  ...  200
5    {'lon': 18.46, 'lat': -66.1}  ...  200

[6 rows x 13 columns]
[2024-02-10T23:18:17.338+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T23:18:17.348+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=extract, execution_date=20240210T231803, start_date=20240210T231806, end_date=20240210T231817
[2024-02-10T23:18:17.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T23:18:17.567+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
