[2024-02-10T23:10:54.873+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.extract manual__2024-02-10T23:05:21.504357+00:00 [queued]>
[2024-02-10T23:10:54.931+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.extract manual__2024-02-10T23:05:21.504357+00:00 [queued]>
[2024-02-10T23:10:54.941+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T23:10:55.759+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): extract> on 2024-02-10 23:05:21.504357+00:00
[2024-02-10T23:10:55.816+0000] {standard_task_runner.py:60} INFO - Started process 73 to run task
[2024-02-10T23:10:55.829+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'extract', 'manual__2024-02-10T23:05:21.504357+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpqbcp6m6_']
[2024-02-10T23:10:55.845+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask extract
[2024-02-10T23:10:56.176+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.extract manual__2024-02-10T23:05:21.504357+00:00 [running]> on host dffe7b1315cb
[2024-02-10T23:10:56.687+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T23:05:21.504357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T23:05:21.504357+00:00'
[2024-02-10T23:10:58.748+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-34.61, -58.38) OK.
[2024-02-10T23:11:00.313+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-56.18, -34.9) OK.
[2024-02-10T23:11:01.808+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (135.18, 34.69).
[2024-02-10T23:11:03.288+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-0.12, 51.5) OK.
[2024-02-10T23:11:04.704+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (-118.24, 34.05).
[2024-02-10T23:11:06.315+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-60.02, -3.1) OK.
[2024-02-10T23:11:07.781+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-80.19, 25.77) OK.
[2024-02-10T23:11:09.294+0000] {etl_dag.py:79} INFO - Extracción de datos para la ciudad (-66.1, 18.46) OK.
[2024-02-10T23:11:10.704+0000] {etl_dag.py:81} INFO - Error en la solicitud a la API para la ciudad (121.45, 31.22).
[2024-02-10T23:11:10.987+0000] {etl_dag.py:88} INFO - Contenido del DataFrame después de la extracción:
                            coord  ...  cod
0  {'lon': -58.38, 'lat': -34.61}  ...  200
1   {'lon': -34.9, 'lat': -56.18}  ...  200
2     {'lon': 51.5, 'lat': -0.12}  ...  200
3    {'lon': -3.1, 'lat': -60.02}  ...  200
4   {'lon': 25.77, 'lat': -80.19}  ...  200
5    {'lon': 18.46, 'lat': -66.1}  ...  200

[6 rows x 13 columns]
[2024-02-10T23:11:11.004+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T23:11:11.066+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=extract, execution_date=20240210T230521, start_date=20240210T231054, end_date=20240210T231111
[2024-02-10T23:11:11.281+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T23:11:11.453+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
